### PR TITLE
ConfigureServiceHostBase needed to to run before behaviors used

### LINKED ISSUE #193: Add custom contract behavior by modifying ServiceHostBase doesn't fully work
“by hand” configuring custom ContractBehaviors test variation failed when validating the behavior implementation, sample test code in PR #151 :
```
builder.ConfigureServiceHostBase<ContractBehaviorBasic_ByHand_Service>(serviceHost =>
                            {
                                var cb = new ServiceContract.CustomContractBehaviorAttribute();
                                serviceHost.Description.Endpoints[0].Contract.ContractBehaviors.Add(cb);
                            });
```
Validation from service side:
1. the custom behavior can be found in OperationContext.Current.Host.Description.Endpoints[0].Contract.ContractBehaviors - **PASS**
2. the implemented method of the custom contract behavior (e.g. ApplyDispatchBehavior(...)) should be invoked - **FAIL**

**Note:**
Test variation which use the custom behavior as an attribute decorating the contract interface works, the ApplyDispatchBehavior(...) implementation would be invoked with test flag being set as expected when applying the attribute.

### PR DESCRIPTION
**Pull request by mconnew**
Fixes #193  
Also added IEndpointBehavior test

### CODE REVIEW

**Comment by mconnew** [comment]
@birojnayak, can you review this. I discovered this issue which apparently there was already an open issue for and I had intended to fix for GA anyway while working on an example for #307

File: src/CoreWCF.Primitives/src/CoreWCF/Description/DispatcherBuilder.cs [hunk 1]
```diff
@@ -691,9 +691,9 @@ private static bool HaveCommonInitiatingActions(EndpointFilterProvider x, Endpoi
                 serviceHost.Description.Endpoints.Add(serviceEndpoint);
             }
 
-            InitializeServiceHost(serviceHost, services);
             ServiceConfigurationDelegateHolder<TService> configDelegate = services.GetService<ServiceConfigurationDelegateHolder<TService>>();
             configDelegate?.Configure(serviceHost);
+            InitializeServiceHost(serviceHost, services);
```
Comment (birojnayak) [inline src/CoreWCF.Primitives/src/CoreWCF/Description/DispatcherBuilder.cs:696]: make sense... you will have all behavior context populated and being sent to delegate to modify or add...

**Review by birojnayak — APPROVED** [review]
you made it better..
