### PR TITLE
Cleanup DI handling, fix allowing ServiceBehaviorAttribute via DI

### LINKED ISSUE #355: DI is checked for instances of IServiceBehavior after we ensure there's a ServiceBehaviorAttribute
This is preventing injecting a ServiceBehaviorAttribute via DI. The logic needs to be changed to check for IServiceBehavior instances in DI before we check if we have an instance of ServiceBehaviorAttribute in the set of behaviors.
This was discovered as part of #353

### PR DESCRIPTION
**Pull request by mconnew**
Fixes #355
Fixes other issues brought up in #353

### CODE REVIEW

File: src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceDescription.cs [hunk 1]
```diff
@@ -77,11 +80,24 @@ public string ConfigurationName
 
         public Type ServiceType { get; set; }
 
-        internal static void AddBehaviors<TService>(ServiceDescription serviceDescription) where TService : class
+        internal static void AddBehaviors<TService>(ServiceDescription serviceDescription, IEnumerable<IServiceBehavior> injectedBehaviors = null) where TService : class
         {
             TypeLoader<TService>.ApplyServiceInheritance<IServiceBehavior, KeyedByTypeCollection<IServiceBehavior>>(
                 serviceDescription.Behaviors, GetIServiceBehaviorAttributes);
 
+            if (injectedBehaviors != null)
```
Comment (birojnayak) [inline src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceDescription.cs:88]: how this is different from ConfigureServiceHostBase ?

Comment (mconnew) [reply src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceDescription.cs:88]: ConfigureServiceHostBase allows you to provide a delegate which is passed the ServiceHostBase instance for you to modify. This is the mechanism of allowing you to add an implementation of IServiceBehavior to DI and have that automatically added to the description. The problem was that the DI behaviors were being added too late which meant if you tried to add a ServiceBehaviorAttribute to DI, it would fail because the automatic add if missing logic had already ran.

File: src/CoreWCF.Http/tests/Services/TestBasicScenariosService.cs [hunk 2]
```diff
@@ -7,7 +7,7 @@
 
 namespace Services
 {
-    [ServiceBehavior]
+    //[ServiceBehavior]
```
Comment (birojnayak) [inline src/CoreWCF.Http/tests/Services/TestBasicScenariosService.cs:10]: you want this behavior to be there ?

File: src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceDescription.cs [hunk 3]
```diff
@@ -231,6 +243,26 @@ private static void GetIServiceBehaviorAttributes(Type currentServiceType, Keyed
             }
         }
 
+        internal static void SetupSingleton<TService>(ServiceDescription serviceDescription, IServiceProvider services) where TService : class
+        {
+            ServiceBehaviorAttribute serviceBehavior = serviceDescription.Behaviors.Find<ServiceBehaviorAttribute>();
+            Debug.Assert(serviceBehavior != null, "EnsureServiceBehavior should have ensured the serviceBehavior");
```
Comment (birojnayak) [inline src/CoreWCF.Primitives/src/CoreWCF/Description/ServiceDescription.cs:249]: should we these message to resource.xml or some format... or you want to keep as it it

File: src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs [hunk 4]
```diff
@@ -52,69 +54,44 @@ internal override object DisposableInstance
...
-                else
-                {
-                    serviceBehavior.InstanceProvider = new DependencyInjectionInstanceProvider(_serviceProvider, typeof(TService));
-                    if (serviceInstanceUsedAsABehavior == null && instance is IDisposable disposable)
-                    {
-                        disposable.Dispose();
-                    }
-                }
+                // If using Single, then ServiceBehavior fetched/created the instance and need to set on SingletonInstance
+                Debug.Assert(serviceInstanceUsedAsABehavior != null, "Service behavior should have created a singleton instance");
```
Comment (birojnayak) [inline src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs:84]: same as above.. for these message, should we leave as is

**Review by birojnayak — APPROVED** [review]

File: src/CoreWCF.Http/tests/Services/TestBasicScenariosService.cs (hunk 2 above)
Comment (mconnew) [reply src/CoreWCF.Http/tests/Services/TestBasicScenariosService.cs:10]: Oops, that was left over from before I had explicit tests. I'll fix that.
